(define (domain extended_vanilla_world)
  (:requirements :strips)
  (:predicates
   (adj ?square-1 ?square-2)
   (white ?square)

   (at ?who ?square)
   (have ?who ?what)
   (close-to ?what ?closet)
   (closet ?closet)
   (machine ?machine)
   (loaded ?what ?machine)
   (runned ?what ?machine)
   (object ?what)
   (takeable ?what)
   (robot ?who)
   (isfree ?who))
  (:action move
    :parameters (?who ?from ?to)

    :precondition (and (robot ?who)
		       (at ?who ?from)
		       (adj ?from ?to)
		       (white ?to)
		       (white ?from)
	)

    :effect (and (not (at ?who ?from))
		 (at ?who ?to))
  	)

  (:action pick-up
    :parameters (?who ?what ?where-who ?where-what)
    :precondition (and (robot ?who)
		       (takeable ?what)
		       (at ?who ?where-who)
		       (at ?what ?where-what)
		       (adj ?where-who ?where-what))
    :effect (and (have ?who ?what)
		 (not (at ?what ?where-what))
		 (not (isfree ?who)))
    	)

  (:action load
    :parameters (?who ?what ?where-who ?machine ?where-machine)
    :precondition (and (have ?who ?what)
		       (robot ?who)
		       (machine ?machine)
		       (at ?machine ?where-machine)
		       (object ?what)
		       (at ?who ?where-who)
		       (adj ?where-who ?where-machine))
    :effect (and (at ?what ?where-machine)
                 (loaded ?what ?machine) 
                 (not (have ?who ?what))
		 (isfree ?who))
	)

  (:action run
    :parameters (?who ?where-who ?machine ?where-machine ?what)
    :precondition (and (loaded ?what ?machine) 
                       (isfree ?who)
		       (robot ?who)
		       (machine ?machine)
		       (at ?who ?where-who)
		       (at ?machine ?where-machine)
		       (adj ?where-who ?where-machine))
    :effect (and (runned ?what ?machine))
    	)	

  (:action tidy-up
    :parameters (?who ?what ?where-who ?closet ?where-closet)
    :precondition (and (have ?who ?what)
		       (closet ?closet)
		       (at ?closet ?where-closet)
		       (takeable ?what)
		       (at ?who ?where-who)
		       (adj ?where-who ?where-closet))
    :effect (and (close-to ?what ?closet) 
		 (not (have ?who ?what)))
	)
)


